# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  tags:
    - fe-gitlab2	
  script:
  - mkdir .public
  - cp -r example/build/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
